document.addEventListener("DOMContentLoaded",()=>{const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;
const progress=$(".scroll-progress span");const header=$(".site-header");const onScroll=()=>{const max=document.documentElement.scrollHeight-innerHeight; if(progress)progress.style.width=(max>0?scrollY/max*100:0)+"%"; if(header)header.classList.toggle("scrolled",scrollY>40)};addEventListener("scroll",onScroll,{passive:true});onScroll();
const toggle=$(".mobile-toggle"),nav=$("#siteNav");if(toggle&&nav){toggle.addEventListener("click",()=>{const open=nav.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open));toggle.setAttribute("aria-label",open?"إغلاق القائمة":"فتح القائمة")});$$("a",nav).forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");toggle.setAttribute("aria-expanded","false");toggle.setAttribute("aria-label","فتح القائمة")}))}
const slides=$$(".hero-slide"),dots=$$(".dot");let current=0,timer;if(slides.length){const show=i=>{current=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle("active",n===current));dots.forEach((d,n)=>{d.classList.toggle("active",n===current);d.setAttribute("aria-selected",String(n===current))})};dots.forEach(d=>d.addEventListener("click",()=>show(Number(d.dataset.slide))));if(!reduced)timer=setInterval(()=>show(current+1),5500);document.addEventListener("visibilitychange",()=>{if(document.hidden){clearInterval(timer)}else if(!reduced)timer=setInterval(()=>show(current+1),5500)})}
const tabs=$$(".tab-btn"),buy=$("#buyForm"),rent=$("#rentForm");tabs.forEach(btn=>btn.addEventListener("click",()=>{const isBuy=btn.dataset.tab==="buy";tabs.forEach(b=>{const active=b===btn;b.classList.toggle("active",active);b.setAttribute("aria-selected",String(active))});buy?.classList.toggle("hidden",!isBuy);rent?.classList.toggle("hidden",isBuy)}));
const setStatus=(el,msg)=>{if(el)el.textContent=msg};
buy?.addEventListener("submit",e=>{e.preventDefault();const d=Object.fromEntries(new FormData(buy));location.href="inventory.html?make="+encodeURIComponent(d.make||"")+"&price="+encodeURIComponent(d.price||"")+"&year="+encodeURIComponent(d.year||"")});
rent?.addEventListener("submit",e=>{e.preventDefault();const d=Object.fromEntries(new FormData(rent));if(d.pickup>d.return){setStatus($("#searchStatus"),"تأكد أن تاريخ الإعادة بعد تاريخ الاستلام.");return}location.href="rental.html?type="+encodeURIComponent(d.type||"")+"&pickup="+encodeURIComponent(d.pickup)+"&return="+encodeURIComponent(d.return)});
$$("[data-action='save']").forEach(btn=>btn.addEventListener("click",()=>{btn.classList.toggle("saved");const icon=$("i",btn);icon?.classList.toggle("fa-regular");icon?.classList.toggle("fa-solid");setStatus($("#searchStatus"),btn.classList.contains("saved")?"تم حفظ السيارة في هذه الجلسة التجريبية.":"تمت إزالة السيارة من المحفوظات التجريبية.")}));
$$("[data-action='share']").forEach(btn=>btn.addEventListener("click",async()=>{const card=btn.closest(".car-card"),name=$("h3",card)?.textContent||"سيارة";try{await navigator.clipboard.writeText(location.href+"#"+encodeURIComponent(name));setStatus($("#searchStatus"),"تم نسخ رابط المشاركة.");}catch{setStatus($("#searchStatus"),"تعذر النسخ تلقائيًا. استخدم مشاركة المتصفح.")}}));
const inventory=$("#inventoryGrid");if(inventory){const cars=[["Toyota","Camry 2026","Sedan","85,000","0 كم","https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1000&q=82"],["Hyundai","Elantra 2026","Sedan","65,000","0 كم","https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=82"],["Ford","Explorer 2025","SUV","145,000","15,000 كم","https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1000&q=82"],["BMW","520i 2026","Luxury","245,000","0 كم","https://images.unsplash.com/photo-1555215695-3004980adade?auto=format&fit=crop&w=1000&q=82"]];const params=new URLSearchParams(location.search);const make=$("#filterMake"),type=$("#filterType"),sort=$("#sortCars");if(make)make.value=params.get("make")||"";const render=()=>{let list=cars.filter(c=>(!make?.value||c[0]===make.value)&&(!type?.value||c[2]===type.value));if(sort?.value==="price-asc")list.sort((a,b)=>parseInt(a[3].replace(/,/g,""))-parseInt(b[3].replace(/,/g,"")));if(sort?.value==="price-desc")list.sort((a,b)=>parseInt(b[3].replace(/,/g,""))-parseInt(a[3].replace(/,/g,"")));inventory.innerHTML=list.map(c=>'<article class="car-card"><div class="car-image"><img src="'+c[5]+'" alt="'+c[0]+" "+c[1]+'" loading="lazy" decoding="async"><span class="car-badge">DEMO</span></div><div class="car-body"><div class="car-top"><div><span class="muted">'+c[0]+'</span><h3>'+c[1]+'</h3></div><strong>'+c[3]+' <small>ر.س</small></strong></div><div class="specs"><span>'+c[4]+'</span><span>أوتوماتيك</span><span>بنزين</span></div><a href="contact.html?car='+encodeURIComponent(c[0]+" "+c[1])+'" class="card-cta">استفسر عن السيارة <span>↗</span></a></div></article>').join("");$("#inventoryEmpty")?.classList.toggle("hidden",!list.length)};[make,type,sort].forEach(x=>x?.addEventListener("change",render));render()}
const rentalPage=$("#rentalPageForm");rentalPage?.addEventListener("submit",e=>{e.preventDefault();const d=Object.fromEntries(new FormData(rentalPage));if(d.pickup>d.return){setStatus($("#rentalStatus"),"تأكد أن تاريخ الإعادة بعد تاريخ الاستلام.");return}setStatus($("#rentalStatus"),"تم تجهيز طلبك التجريبي. يمكنك الآن التواصل عبر واتساب.");const text="طلب تأجير تجريبي\nالفئة: "+d.type+"\nالاستلام: "+d.pickup+"\nالإعادة: "+d.return+"\nملاحظات: "+(d.note||"—");navigator.clipboard?.writeText(text).catch(()=>{});});
const contact=$("#contactForm");const carField=$("#contactCar");if(carField)carField.value=new URLSearchParams(location.search).get("car")||"";contact?.addEventListener("submit",e=>{e.preventDefault();const d=Object.fromEntries(new FormData(contact));const text="استفسار تجريبي من "+d.name+"\nالسيارة/الخدمة: "+d.car+"\nالهاتف: "+d.phone+"\nالرسالة: "+d.message;navigator.clipboard?.writeText(text).then(()=>setStatus($("#contactStatus"),"تم تجهيز الرسالة ونسخها. هذه نسخة DEMO ولا يتم إرسالها.")).catch(()=>setStatus($("#contactStatus"),"تم تجهيز الرسالة. هذه نسخة DEMO ولا يتم إرسالها."))});
const reveal=$$(".car-card,.benefit-grid article,.service-rows article");if("IntersectionObserver"in window&&!reduced){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.style.opacity="1";e.target.style.transform="none";io.unobserve(e.target)}}),{threshold:.08});reveal.forEach((el,i)=>{el.style.opacity="0";el.style.transform="translateY(18px)";el.style.transition="opacity .5s ease "+Math.min(i*.04,.24)+"s,transform .5s ease "+Math.min(i*.04,.24)+"s";io.observe(el)})}});