(()=>{"use strict";const C=window.NAQA_CONFIG||{},$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;
$$("[data-phone]").forEach(a=>{a.href="tel:"+(C.phoneE164||"+966500000000");a.textContent=C.phoneDisplay||"+966 50 000 0000"});$$("[data-email]").forEach(a=>{a.href="mailto:"+(C.email||"hello@example.com");a.textContent=C.email||"hello@example.com"});$$("[data-wa]").forEach(a=>a.href="https://wa.me/"+(C.whatsappNumber||"966500000000")+"?text="+encodeURIComponent("مرحباً، أود الاستفسار عن خدمات نقاء (نموذج تجريبي)."));$$("[data-year]").forEach(e=>e.textContent=new Date().getFullYear());
const header=$("#site-header"),bar=$(".scroll-progress");let busy=false;function scrollState(){header?.classList.toggle("scrolled",scrollY>12);if(bar){let max=document.documentElement.scrollHeight-innerHeight;bar.style.width=(max>0?Math.min(100,scrollY/max*100):0)+"%"}busy=false}addEventListener("scroll",()=>{if(!busy){requestAnimationFrame(scrollState);busy=true}},{passive:true});scrollState();
const toggle=$(".menu-toggle"),nav=$("#primary-nav");function close(){toggle?.setAttribute("aria-expanded","false");toggle?.setAttribute("aria-label","فتح القائمة");nav?.classList.remove("open")}toggle?.addEventListener("click",()=>{let open=toggle.getAttribute("aria-expanded")!=="true";toggle.setAttribute("aria-expanded",String(open));toggle.setAttribute("aria-label",open?"إغلاق القائمة":"فتح القائمة");nav?.classList.toggle("open",open)});nav?.addEventListener("click",e=>{if(e.target.closest("a"))close()});document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});document.addEventListener("click",e=>{if(nav?.classList.contains("open")&&!nav.contains(e.target)&&!toggle?.contains(e.target))close()});addEventListener("resize",()=>{if(innerWidth>767)close()});$("[data-dismiss]")?.addEventListener("click",()=>$("#announcement")?.remove());
const els=$$(".reveal");if("IntersectionObserver"in window&&!reduced){let io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");io.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>io.observe(e))}else els.forEach(e=>e.classList.add("visible"));
const today=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);$$('input[type="date"]').forEach(i=>i.min=today);$$("[data-service]").forEach(b=>b.addEventListener("click",()=>{$$("[data-service]").forEach(x=>x.setAttribute("aria-selected",String(x===b)));let h=$('input[name="service"]');if(h)h.value=b.dataset.service}));
const phone=/^(?:(?:\+?966)|0)?5\d{8}$/;function validate(form){let first=null;$$("input,select,textarea",form).forEach(x=>{if(x.type==="hidden")return;let v=x.value.trim(),err="";if(x.required&&!v)err="هذا الحقل مطلوب.";else if(x.name==="phone"&&v&&!phone.test(v.replace(/[\s()-]/g,"")))err="أدخل رقم جوال سعوديًا صحيحًا.";else if(x.type==="email"&&v&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))err="تحقق من صيغة البريد الإلكتروني.";else if(x.type==="date"&&v&&v<today)err="اختر اليوم أو تاريخًا لاحقًا.";x.setAttribute("aria-invalid",String(!!err));let out=x.closest(".field")?.querySelector(".error");if(out)out.textContent=err;if(err&&!first)first=x});first?.focus();return !first}
$$(".demo-form").forEach(form=>{form.addEventListener("input",e=>{if(e.target.matches("input,select,textarea")){e.target.setAttribute("aria-invalid","false");let er=e.target.closest(".field")?.querySelector(".error");if(er)er.textContent=""}});form.addEventListener("submit",e=>{e.preventDefault();let fb=$(".feedback",form);if(!validate(form)){if(fb){fb.hidden=false;fb.textContent="يرجى مراجعة الحقول المحددة."}return}let btn=$('button[type="submit"]',form),label=$(".btn-label",btn),old=label?.textContent;btn.disabled=true;if(label)label.textContent="جارٍ تجهيز المعاينة…";setTimeout(()=>{btn.disabled=false;if(label)label.textContent=old||"إرسال";if(fb){fb.hidden=false;fb.textContent="تم تسجيل طلبك التجريبي. سيتواصل معك الفريق لتأكيد التفاصيل عند ربط الموقع بخدمة فعلية. لم تُرسل أي بيانات."}form.reset()},400)})});
$$(".faq-question").forEach(b=>b.addEventListener("click",()=>{let open=b.getAttribute("aria-expanded")==="true",p=$("#"+b.getAttribute("aria-controls"));b.setAttribute("aria-expanded",String(!open));if(p)p.hidden=open}));
const data={shirt:["القميص الأبيض","كي متوازن، ياقة مرتبة، واهتمام بالتفاصيل اليومية.",C.images?.shirt,"قميص أبيض مرتب بعناية"],suit:["البدلة الرسمية","مراعاة بنية القطعة والياقة وانسيابية القماش.",C.images?.suit,"بدلة رسمية"],fabric:["القماش الحساس","مراجعة تعليمات العناية والخامة قبل اختيار الطريقة.",C.images?.fabric,"تفاصيل قماش ناعم"]};$$("[data-gallery]").forEach(b=>b.addEventListener("click",()=>{let d=data[b.dataset.gallery];if(!d)return;$$("[data-gallery]").forEach(x=>x.setAttribute("aria-selected",String(x===b)));let im=$("#gallery-image");if(im){im.src=d[2];im.alt=d[3]}if($("#gallery-title"))$("#gallery-title").textContent=d[0];if($("#gallery-description"))$("#gallery-description").textContent=d[1]}));
$$("[data-area]").forEach(b=>b.addEventListener("click",()=>{$$("[data-area]").forEach(x=>{x.classList.toggle("active",x===b);x.setAttribute("aria-pressed",String(x===b))});if($("#area-selected"))$("#area-selected").textContent=b.dataset.area}));
const reviews=[["أحب أن تكون طريقة العناية واضحة من البداية، وأن تعود القطع مرتبة كما أتوقع.","مها — نموذج تجريبي"],["اختيار موعد الاستلام مسبقًا يجعل الخدمة أسهل في التخطيط.","نورة — نموذج تجريبي"],["أقدّر الاهتمام بتفاصيل القماش بدل التعامل مع كل القطع بالطريقة نفسها.","ريم — نموذج تجريبي"]];let ri=0;function review(){if($("#review-text"))$("#review-text").textContent=reviews[ri][0];if($("#review-name"))$("#review-name").textContent=reviews[ri][1];if($("#review-progress"))$("#review-progress").style.width=((ri+1)/reviews.length*100)+"%"}$("[data-review-prev]")?.addEventListener("click",()=>{ri=(ri+reviews.length-1)%reviews.length;review()});$("[data-review-next]")?.addEventListener("click",()=>{ri=(ri+1)%reviews.length;review()});
})();